[package]
name = "file_sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# This library is for libssh2 bindings for rust inorder to set up an ssh tunnel for 2-way data transfer.
ssh2 = "0.9"